namespace Cmhd.SuccintDataStructures.Tests

open Expecto.Tests

module Runner =
    // [<EntryPoint>] 
    // Removed because of the autogenerated test main, make that main
    // reference this one
    let main argv = 
        runTestsInAssembly defaultConfig argv

        // let returnCode = runTestsInAssembly defaultConfig argv
        // System.Console.ReadKey() |> ignore
        // returnCode